# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-03 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('PhoneNumber', models.BigIntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('CV', models.FileField(upload_to=b'')),
            ],
        ),
    ]
